### ISSUE TITLE
OIDC/Authelia: No redirection

### ISSUE THREAD

**Issue by cite** [sissbruecker/linkding#1016]
First of all, thank you very much for the great work. This software made my life much, much easier.

However, I had working OIDC with Authelia up to some point, but somehow after migrating Authelia's configuration to the lates 4.39.x version (silencing all the deprecation warnings), I can't login to Linkding with OIDC anymore - the auth request is successful, yet there is no redirect back from Authelia to Linkding. In the below configuration examples, I simply replaced all occurences of my real domain with `example.com`:

```yaml
# environment variables from docker-compose.yml
      LD_ENABLE_OIDC: "True"
      OIDC_OP_AUTHORIZATION_ENDPOINT: https://auth.example.com/api/oidc/authorization
      OIDC_OP_TOKEN_ENDPOINT: https://auth.example.com/api/oidc/token
      OIDC_OP_USER_ENDPOINT: https://auth.example.com/api/oidc/userinfo
      OIDC_OP_JWKS_ENDPOINT: https://auth.example.com/jwks.json
      OIDC_RP_CLIENT_ID: linkding
      OIDC_RP_CLIENT_SECRET: "very secret"
```

Authelia configuration:

```yaml
identity_providers:
  oidc:
    clients:
      - client_id: linkding
        client_name: Linkding
        client_secret: "very secret"
        public: false
        token_endpoint_auth_method: client_secret_post
        authorization_policy: 'one_factor'
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://ld.i.example.com/oidc/callback/
```

I tried switching to public PKCE, and while the authorization continues to work, there is still no redirect. Authelia's logs aren't very helpful, either:

```authelia  | time="2025-03-17T12:45:40+01:00" level=debug msg="Authorization Request with id 'd45b4956-b690-46c7-8b6e-0c811bbdd9d4' on client with id 'linkding' is being processed" method=GET path=/api/oidc/authori
zation remote_ip=1.2.3.4
authelia  | time="2025-03-17T12:45:43+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'cite'" method=POST path=/api/firstfactor remote_ip=1.2.3.4
authelia  | time="2025-03-17T12:45:43+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'cite'" method=POST path=/api/firstfactor remote_ip=1.2.3.4
```

I realize this is probably not a bug in Linkding, but I have no idea where to look for clues. Using https://oidcdebugger.com/ with the values from my configuration, I'm able to successfully authenticate _and_ get redirected. Authelia version is 4.39.0, and Linkding version is 1.39.1.
