### ISSUE TITLE
reader mode custom css

### ISSUE THREAD

**Issue by AlexAxthelm** [sissbruecker/linkding#1042]
Hi, loving linkding so far, and the reader mode (introduced in #703) is great!

I've been looking to tweak the style in reader mode (mostly changing fonts), but when I use the custom CSS, I can make the changes affect the main layout, but not reader-mode.

Looking at #891 as an example, I updated my custom CSS with

```css
:root {
  --body-font-family: "Atkinson Hyperlegible Next", var(--base-font-family), var(--fallback-font-family);
}
```

which did correctly apply the font to the bookmarks, but not the body text in reader mode. Do you have any suggestions on how to update the style for the reader>
