### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by Sloshy1** [sissbruecker/linkding#153]
I set up Linkding last week some time (perhaps 21st/22nd), unfortunately I cannot remember what version I was running. I'm so far only using it on my LAN and am pretty much using the default setup, except for changing the port it uses to 9999. I've added about 2 pages worth of bookmarks and when I tried to add a bookmark the other day, it tried to pull the name and description from the website but the mini progress bubble kept spinning for a while. Eventually the webpage timed out and linkding became unavailable so I restarted the container and it was stable. I then tried to add the same bookmark and the same thing happened. I've now updated to the latest version and the issue is now even worse. The website seldom loads, and most of the time it displays a white page with `Server Error (500)` on it. There is no firewall in front of it and it's the only container that I've published using port 9999. All other containers on the host are operating normally. I cannot find any logs for linkding within the container either.

Environment Info:
Host - Raspberry Pi 3 Model B Rev 1.2
OS - RaspiOS Buster (Downloaded about 3 weeks ago)

docker-compose.yml

```
version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR}:/etc/linkding/data"
    restart: unless-stopped
```

.env

```
# Docker container name
LD_CONTAINER_NAME=linkding
# Port on the host system that the application should be published on
LD_HOST_PORT=9999
# Directory on the host system that should be mounted as data dir into the Docker container
LD_HOST_DATA_DIR=/docker/linkding/data

# Option to disable URL validation for bookmarks completely
LD_DISABLE_URL_VALIDATION=False
```
