### ISSUE TITLE
use HTTPs instead of HTTP to access the application?

### ISSUE THREAD

**Issue by sprklinginfo** [sissbruecker/linkding#274]
Hi, 
I have a domain with https enabled. I installed the application with the docker-compose method. I can access the Linkding with HTTP (.e.g http://mysite.com:9090), but with the https version, it showed 'The connection has timed out' error. 
My hosting server is an apache server, I can access the default page with https://mysite.com.  Here is the docker-compose.yml file I used:
```
version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
```
How to update this file to ensure I can access linkding by https://mysite.com:9090? 
Thanks!
