### ISSUE TITLE
CSRF verification fails when running linkding behind a proxy such as nginx

### ISSUE THREAD

**Issue by sissbruecker** [sissbruecker/linkding#340]
Since version 1.15.0 linkding uses Django 4.1, which introduces new restrictions to [CSRF handling](https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf-trusted-origins-changes-4-0). This can cause CSRF verification to fail (for example during login) if the app is running behind a proxy and is not properly configured for it.

This needs investigation if the app can provide some default configuration out of the box, otherwise this requires documentation on how to properly configure CSRF when using a proxy.

**Comment by Glide01** [comment]
same here, I'm using apache.

**Comment by sissbruecker** [comment]
Workarounds for the moment:
- Use version 1.14.0. Docker tag is `sissbruecker/linkding:1.14.0`. You will not miss much, there are no critical fixes in the latest release. You can also downgrade, there are no DB migrations between the two versions.
- Properly configure CSRF
  - Create a `custom.py` file
  - Add this line to the file: `CSRF_TRUSTED_ORIGINS = ['https://linkding.domain.com']`,  make sure to use the correct protocol (http or https) and domain
  - Mount the file into the Docker container by adding an additional volume to the Docker run command: `-v custom.py:/etc/linkding/siteroot/settings/custom.py`
  - Create a new container

**Comment by sissbruecker** [comment]
The new CSRF check in Django 4 requires that the values of the `host` and `origin` request headers match. A valid combination would be for example:
```
Host: linkding.domain.com
Origin: https://linkding.domain.com
```

From some testing it seems that Nginx changes the value of the `host` request header to whatever is used in the `proxy_pass` directive. So if you use `proxy_pass http://localhost:9090`, then the `host` header is changed to `localhost:9090`, which causes the CSRF check to fail. The same does not happen when using Caddy, which just relays the original `host` header.

So another solution is to configure Nginx to relay the original host header:
```
    location / {
        proxy_pass http://localhost:9090;
        proxy_set_header Host $http_host;
    }
```

**Comment by 0x9394** [comment]
nginx _subpath_ config,
*  `custom.py` method works with latest image. 
*  `proxy_set_header Host $http_host;` option makes no different. 
* * with custom.py subpath url will work
* * without custom.py subpath url will goes to 403 forbidden

**Comment by sissbruecker** [comment]
Tested forwarding the `host` header with a sub path in Nginx, works fine for me. Using a context path doesn't make any difference for the CSRF check, as neither the `Host` or `Origin` header contain the path, and the `proxy_set_header Host $http_host;` directive will also not add the path.

I'm testing with the following docker-compose setup:
```
version: '3'

services:
  linkding:
    ports:
      - 9090
    environment:
      LD_CONTEXT_PATH: linkding/
      LD_SUPERUSER_NAME: admin
      LD_SUPERUSER_PASSWORD: admin
    image: sissbruecker/linkding:latest
  nginx:
    image: nginx:1.22.0
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - linkding
```

And this is `nginx.conf`:
```
server {
    listen 80;
    server_name _;

    location /linkding/ {
        proxy_pass http://linkding:9090;
        proxy_set_header Host $http_host;
    }
}
```
