### ISSUE TITLE
1.0.5 Helm chart broke my deployment

### ISSUE THREAD

**Issue by kalmarz** [sissbruecker/linkding#477]
I tried to upgrade from chart version `0.3.1` to the latest `1.0.5` (at the time of writing) and it failed with the error: `reconciliation failed: Helm upgrade failed: cannot patch "linkding" with kind Deployment: Deployment.apps "linkding" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "storage-volume"`

I have a pre-baked PV and PVC that I refer to and they've worked quite well so far.
```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /home/....
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume
  namespace: linkding
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    storage: 10Gi
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: pascaliske
  namespace: linkding
spec:
  interval: 60m
  url: https://charts.pascaliske.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  interval: 30s
  chart:
    spec:
      chart: linkding
      version: "0.3.1" # <- I only changed this line to 1.0.5
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: linkding
      interval: 60m
  values:
    persistentVolumeClaim:
      create: false
      existingPersistentVolumeClaim: storage-volume
---
```

The cluster is managed with [FluxCD](https://fluxcd.io), hence the `HelmRepository` and `HelmRelease` objects. What I saw among the k8s events was the Helm release tried to provision another volume, named `linkding-storage` and disregarded my pre-made PV and PVC although they were there and named exactly as the release required. Any pointer would be greatly appreciated.
