### ISSUE TITLE
Authentik auth proxy not working

### ISSUE THREAD

**Issue by JesseWebDotCom** [sissbruecker/linkding#486]
Hello. I tried to setup auth proxy authentication but I end up stuck at the login page.

I have configured my authentik server with a forward auth (single application) proxy provider for linkding (similar to how I have other apps configured). Part of the response header (configured in my Traefik middleware) includes "X-authentik-username". 

I set my docker compose environment section:
```yaml
    environment:
      - LD_ENABLE_AUTH_PROXY=True
      - LD_AUTH_PROXY_USERNAME_HEADER=X_AUTHENTIK_USERNAME
      - LD_AUTH_PROXY_LOGOUT_URL=${LINKDING_PROXY_LOGOUT_URL}
```

I have the LINKDING_PROXY_LOGOUT_URL environment variable (ex. auth.domain_name_here.com/outpost.goauthentik.io/sign_out) defined in another env file I call with compose. 

I deleted the container and data folder and compose up my environment. I get prompted for authentik authentication (which works successfully) and then I'm sent and stuck at  https://linkding.domain_name_here.com/login/?next=/bookmarks (which expects me to put in a username and password). My linkding data folder is empty.

What am I missing?

**Comment by strandundmeer** [comment]
Hi @JesseWebDotCom,

i mae the same mistake and missed a tiny little part of the documentation:
You have to prefix the header with HTTP_

So this one should work: HTTP_X_AUTHENTIK_USERNAME

Hope this helps!

**Comment by JesseWebDotCom** [comment]
Thanks, I’ll give that a shot

**Comment by JesseWebDotCom** [comment]
No as I decided on sticking with safari/iOS bookmark management (much easier for me across my devices).

**Comment by joshoram80** [comment]
I am also having the same issue. Using LD_AUTH_PROXY_USERNAME_HEADER=HTTP_X_AUTHENTIK_USERNAME does not seem to work for me

**Comment by strandundmeer** [comment]
I use Authentik with Linkding without issues.

just for reference, I have the following in my docker .env
LD_ENABLE_AUTH_PROXY=True
LD_AUTH_PROXY_USERNAME_HEADER=HTTP_X_AUTHENTIK_USERNAME
LD_AUTH_PROXY_LOGOUT_URL=Authentik-URL/outpost.goauthentik.io/sign_out

you should also make sure that you are adding the correct headers in your reverse-proxy config.

**Comment by joshoram80** [comment]
I have literally the same variables in my .env

My traefik Authentik config 

```
middlewares-authentik:
      forwardAuth:
        address: "http://authentik_server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
          - authorization
```

Authentik works for me with every other service, just not Linkding, and because there is no errors or anything I can't diagnose why. I even have other services that use X-authentik-username for auth and they work too. I'm stumped.
