### ISSUE TITLE
CSRF error on second time clicking Remove or Archive

### ISSUE THREAD

**Issue by ar-nelson** [sissbruecker/linkding#523]
I have a docker-compose setup with Linkding behind Authelia and Caddy. Most the the application works, but, when I click the Remove or Archive button on any entry for the *second time* on a given page load, it returns HTTP 403 and a CSRF error. The first click works, and refreshing the page will make it work again, once.

I don't know if this is related to https://github.com/sissbruecker/linkding/issues/340. I tried the fix from that issue, but it didn't seem to do anything.

Here is my docker-compose setup for linkding; it's the mustache template used in my Docker config generator, so my local domain and passwords are redacted.

**docker-compose.yml** (relevant parts only)

```yaml
  proxy:
    image: caddy:2.6.2
    hostname: proxy
    domainname: proxy.{{ DOMAIN }}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      default:
        # auth always points to proxy because OAuth requires HTTPS
        aliases:
          - auth
          - auth.{{ DOMAIN }}
 auth:
    image: authelia/authelia:4
    hostname: auth
    domainname: auth.{{ DOMAIN }}
    restart: unless-stopped
    env_file:
      - ./config/auth.env
    volumes:
      - ./config/auth:/config:ro
      - ./config/secrets:/secrets:ro
    networks:
      default:
        aliases:
          - auth-internal
          - auth-internal.{{ DOMAIN }}
  links:
    image: sissbruecker/linkding:latest
    hostname: links
    domainname: links.{{ DOMAIN }}
    restart: unless-stopped
    env_file:
      - ./config/links.env
    networks:
      default:
       aliases:
          - links
          - links.{{ DOMAIN }}
```

**config/links.env**

```ini
LD_DB_ENGINE=postgres
LD_DB_HOST=db.{{ DOMAIN }}
LD_ENABLE_AUTH_PROXY=True
LD_AUTH_PROXY_USERNAME_HEADER=HTTP_REMOTE_USER
LD_AUTH_PROXY_LOGOUT_URL=https://auth.{{ DOMAIN }}/logout
LD_CSRF_TRUSTED_ORIGINS=https://links.{{ DOMAIN }},http://links.{{ DOMAIN }},https://auth.{{ DOMAIN }},http://auth-internal.{{ DOMAIN }}
LD_DB_PASSWORD={{ POSTGRES_LINKDING_PASSWORD }}
```

**config/Caddyfile** (relevant parts only)

```
auth.{{ DOMAIN }} {
    handle {
        reverse_proxy auth-internal.{{ DOMAIN }}:9091
    }
}
links.{{ DOMAIN }} {
    handle {
        @notapi not path /api/* /static/*
        forward_auth @notapi auth-internal.{{ DOMAIN }}:9091 {
            uri /api/verify?rd=https://auth.{{ DOMAIN }}
            copy_headers Remote-User
        }
        reverse_proxy links.{{ DOMAIN }}:9090
    }
}
```
