### ISSUE TITLE
Support disabling alphabetical grouping in tag cloud

### ISSUE THREAD

**Issue by jlhg** [sissbruecker/linkding#588]
Different from the alphabetical characters, the Chinese characters are diverse and will result in one line, one tag. 
It would be nice to have an option to disable the line break between groups.

Currently I use the Stylus for a workaround:

```css
.tag-cloud .group {
  display: inline;
}
```
