### ISSUE TITLE
Probable memory leak

### ISSUE THREAD

**Issue by nstwfdev** [sissbruecker/linkding#634]
Hello there.
Finded already existing issue  https://github.com/sissbruecker/linkding/issues/488#issue-1760278070, but it closed, reopen.

Started from 180mb. But after ~10-12h, `docker stats` said:
`
20d8cd58d036   linkding        0.01%     232MiB / 31.29GiB     0.72%     867kB / 2.16MB    0B / 0B     13
`

docker-compose.yml
```
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
```

.env

```
LD_CONTAINER_NAME=linkding
LD_HOST_PORT=9090
LD_HOST_DATA_DIR=./data

LD_CONTEXT_PATH=
LD_SUPERUSER_NAME=postgres
LD_SUPERUSER_PASSWORD=postgres
LD_DISABLE_BACKGROUND_TASKS=False
LD_DISABLE_URL_VALIDATION=True
LD_ENABLE_AUTH_PROXY=False
LD_AUTH_PROXY_USERNAME_HEADER=
LD_AUTH_PROXY_LOGOUT_URL=
LD_CSRF_TRUSTED_ORIGINS=

LD_DB_ENGINE=postgre
LD_DB_DATABASE=linkding
LD_DB_USER=postgres
LD_DB_PASSWORD=postgres
LD_DB_HOST=postgres
LD_DB_PORT=5432
LD_DB_OPTIONS=
```
