### ISSUE TITLE
Migrate to Ruff

### ISSUE THREAD

**Issue by ab623** [sissbruecker/linkding#707]
Consider migrating to [ruff](https://docs.astral.sh/ruff/) for linting and for formatting.

Ruff already implements the [black formatting ](https://docs.astral.sh/ruff/formatter/#black-compatibility) style mostly, as well as other formatting tools like isort etc.

Generally I use  the following in my `pyproject.toml` file

```toml
[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Warning
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
```

Also consider using precommit to lint and format on the commit, to take the hassle out of running the formatted manually. You can also include the npm formatter at the same time.

For example my `.pre-commit-config.yaml` is as follows:

```yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
