### ISSUE TITLE
High cpu utilisation - via python manage.py run huey -f

### ISSUE THREAD

**Issue by DD5HT** [sissbruecker/linkding#723]
I noticed that: `python manage.py run huey -f` is triggered regularly, creating a high CPU utilization on my machine, is there a simple way to prevent it?

See this screenshot, the previous utilization corresponds to, around 10 services, including grafana, victoria metrics, home assistant and a few other services the new increased utilisation is when running linkding.
![Screenshot 2024-05-04 at 17-22-19 Node Exporter Full - Dashboards - Grafana](https://github.com/sissbruecker/linkding/assets/7716993/2821b689-d50b-4758-b9d8-560ec416ef29)

My config:

```yaml
 linkding:
    container_name: linkding
    image: sissbruecker/linkding:1.30.0-alpine
    ports:
      - "9090:9090"
    volumes:
      - "${DATA_DIR}/linkding:/etc/linkding/data"
    restart: unless-stopped
    environment:
      - LD_CSRF_TRUSTED_ORIGINS=domain
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkding.rule=Host(`domain`)"
      - "traefik.http.routers.linkding.entrypoints=web"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
```
