### ISSUE TITLE
Linkding using 8GB or RAM when idle

### ISSUE THREAD

**Issue by alangrafu** [sissbruecker/linkding#787]
I just realized Linkding is using 8gb of RAM

No Linkding
<img width="789" alt="image" src="https://github.com/user-attachments/assets/f705e1b5-3334-4486-abd8-2a47a415a044">

Yes Linkding
<img width="797" alt="image" src="https://github.com/user-attachments/assets/1da822cd-ad97-4be4-80de-40a08486ca4e">

I don't remember being so RAM greedy in the past.

My docker compose is:

```
version: "3"
services:
  linkding:
    command:
      - ./bootstrap.sh
    container_name: linkding
    environment:
      - PATH=/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - VIRTUAL_ENV=/opt/venv
    hostname: linkding
    image: sissbruecker/linkding:latest
    networks:
      - home_network
    ports:
      - 9090:9090/tcp
    restart: unless-stopped
    volumes:
      - /bigdisk/data/linkding/data:/etc/linkding/data
    working_dir: /etc/linkding
networks:
  home_network:
    external: true
```
