### ISSUE TITLE
Custom CSS font size

### ISSUE THREAD

**Issue by cdaein** [sissbruecker/linkding#891]
In the [how to](https://linkding.link/how-to/) page of the docs, it has an example for updating font size:

```css
html {
  --font-size: 0.75rem;
  --font-size-sm: 0.7rem;
  --font-size-lg: 0.9rem;
}
```

but it doesn't seem to have any effect. The CSS variables are not overridden.

I had to change it to:

```css
:root {
  --font-size: 0.75rem;
  --font-size-sm: 0.7rem;
  --font-size-lg: 0.9rem;
}
```

to make it work although I am not sure what other implications this change may bring to other parts of the app.
