### ISSUE TITLE
OIDC button not showing once configured

### ISSUE THREAD

**Issue by crosbyh** [sissbruecker/linkding#918]
Hello! I am a longtime and very satisfied user of Linkding, thank you for what you provide for this community!

I am having an issue with OIDC configuration in version 1.36.0. Following the Authelia setup guide linked in the docs, I've configured my Linkding compose file as such:

```
services:
  linkding:
    restart: unless-stopped
    container_name: linkding
    image: sissbruecker/linkding:latest-plus
    volumes:
      - ./linkding:/etc/linkding/data
    environment:
      LD_CONTAINER_NAME: linkding
      LD_HOST_PORT: 9090
      LD_HOST_DATA_DIR: ./data
      LD_CONTEXT_PATH: 
#      LD_SUPERUSER_NAME: $LD_SUPERUSER_NAME
#      LD_SUPERUSER_PASSWORD: $LD_SUPERUSER_PASSWORD
      LD_DISABLE_BACKGROUND_TASKS: False
      LD_DISABLE_URL_VALIDATION: False
      LD_CSRF_TRUSTED_ORIGINS: https://links.${DOMAINNAME}
      LD_ENABLE_AUTH_PROXY: False
      LD_ENABLE_OIDC: True
      OIDC_OP_AUTHORIZATION_ENDPOINT: https://auth.${DOMAINNAME}/api/oidc/authorization
      OIDC_OP_TOKEN_ENDPOINT: https://auth.${DOMAINNAME}/api/oidc/token
      OIDC_OP_USER_ENDPOINT: https://auth.${DOMAINNAME}/api/oidc/userinfo
      OIDC_OP_JWKS_ENDPOINT: https://auth.${DOMAINNAME}/jwks.json
      OIDC_RP_CLIENT_ID: ${LINKDING_OIDC_RP_CLIENT_ID}
      OIDC_RP_CLIENT_SECRET: ${LINKDING_OIDC_RP_CLIENT_SECRET}

```
However, the "Sign in with OIDC" button does not appear on my page when I recreate the container. 

Here are the logs from container startup:

```
INFO Secret key file already exists
Operations to perform:
  Apply all migrations: admin, auth, authtoken, bookmarks, contenttypes, sessions
Running migrations:
  No migrations to apply.
2024-11-26 01:27:29,141 INFO Current journal mode: wal
2024-11-26 01:27:29,601 INFO Skip creating initial superuser, LD_SUPERUSER_NAME option is not defined
No legacy tasks found. Skipping task migration
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /static => static
[uwsgi-static] added mapping for /static => data/favicons
[uwsgi-static] added mapping for /static => data/previews
*** Starting uWSGI 2.0.26 (64bit) on [Tue Nov 26 01:27:30 2024] ***
compiled with version: 12.2.0 on 02 October 2024 20:42:59
os: Linux-6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01)
nodename: ba035ddcccc3
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /etc/linkding
writing pidfile to /tmp/linkding.pid
detected binary path: /opt/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1545 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on [::]:9090 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:46349 (port auto-assigned) fd 3
Python version: 3.12.6 (main, Sep 27 2024, 06:10:12) [GCC 12.2.0]
Python main interpreter initialized at 0x7f2239d9ed18
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 274704 bytes (268 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f2239d9ed18 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 19, cores: 2)
spawned uWSGI worker 2 (pid: 21, cores: 2)
*** Stats server enabled on 127.0.0.1:9191 fd: 14 ***
```
Steps Taken So Far:

- Since I previously had header auth enabled on this instance, I tried spinning up a brand new instance with the same config, and the issue persists.
- I am able to docker exec into my container and echo the ENV variables and they are coming through correctly.
- Confirmed that my Authelia / OIDC setup is working properly with my other configured apps

Am I missing part of the config to enable this?
