### ISSUE TITLE
Please revoke this change

### ISSUE THREAD

**Issue by hotlcc** [sissbruecker/linkding#998]
I hope this change can be revoked: https://github.com/sissbruecker/linkding/pull/842 ,It doesn't feel very beautiful. Thank you.

**Comment by sissbruecker** [comment]
No plans to revert this. The bookmark list is harder to go through if there isn't a placeholder taking up that empty space, especially if bookmarks have different heights. It could probably look better - if you have ideas feel free to open an issue with a practical suggestion.

If it bothers you, you can hide the placeholders using custom CSS.

**Comment by hotlcc** [comment]
> No plans to revert this. The bookmark list is harder to go through if there isn't a placeholder taking up that empty space, especially if bookmarks have different heights. It could probably look better - if you have ideas feel free to open an issue with a practical suggestion.
> 
> If it bothers you, you can hide the placeholders using custom CSS.

Maybe you can adjust the layout through CSS styles instead of using placeholder images, which would be too ugly, especially the big black border.

**Comment by hotlcc** [comment]
But custom CSS is a good idea, Think you.

**Comment by hotlcc** [comment]
> But custom CSS is a good idea, Think you.但自定义CSS是一个好主意，认为你.

```css
li[ld-bookmark-item] .preview-image.placeholder {
    border: none;
    background: none;
}
li[ld-bookmark-item] .preview-image.placeholder .img {
    display: none;
}
```
